### ISSUE TITLE
Cannot re-link FFRK account / Account sync frozen at 6 months ago

### ISSUE THREAD

**Issue by SoNick** [Fuitad/FFRKCentral#8]
Hello!
I seem to be having trouble syncing my FFRK account with the FFRK Central website at this time. I had previously set up Account Sync and my profile is showing up at https://www.ffrkcentral.com/profile/KAaP# but the account was last synced six months ago. I have uninstalled the game on a previous phone around that time and then re-installed the game on a new phone about a week and a half ago, I do not know if this is a factor in the account no longer syncing up with the website.

Further, when I log into my FFRK Central account on the website, I do not appear to have my account linked and the button to link is grayed out. Here is an image demonstrating the issue: https://imgur.com/a/4uchB . Will you please assist me in re-linking my FFRK account with my FFRK Central profile?

**Comment by Fuitad** [comment]
Unfortunately, DeNA removed the one time password feature from FFRK so it's no longer possible to link an account to the site :(. 

Sorry :/

**Comment by Fuitad** [comment]
Wait... if your profile still shows on the website, it means your account is still in there. You need to login using the same credentials (or social media account) to be able to sync it again.
